### ISSUE TITLE
start the server return errors!

### ISSUE THREAD

**Issue by jeefs** [shadowsocksr-backup/shadowsocksr#15]
2018-01-11 08:21:15 ERROR    db_transfer.py:260 Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 242, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 367, in pull_db_all_user
    import cymysql
ImportError: No module named cymysql

how can reslove the problem?

**Comment by mosluce** [comment]
@jeefs 
```python
pip install cymysql 
```
could fix it

**Comment by jeefs** [comment]
@mosluce It works fine，thanks
