### ISSUE TITLE
run error  on windows

### ISSUE THREAD

**Issue by wimotek** [shadowsocksr-backup/shadowsocksr#21]
python 2.7.14   openssl 1.02n

2018-03-15 14:27:08 INFO     loading libcrypto from C:\WINDOWS\system32\libeay32
.dll
Traceback (most recent call last):
  File "C:\Python27\Scripts\ssserver-script.py", line 11, in <module>
    load_entry_point('shadowsocks==2.8.2', 'console_scripts', 'ssserver')()
  File "c:\python27\lib\site-packages\shadowsocks\server.py", line 36, in main
    daemon.daemon_exec(config)
  File "c:\python27\lib\site-packages\shadowsocks\daemon.py", line 34, in daemon
_exec
    raise Exception('daemon mode is only supported on Unix')
Exception: daemon mode is only supported on Unix

**Comment by clinkzsu** [comment]
Recently I came across this problem as well as I could not use it on my PC.
