### ISSUE TITLE
ubuntu16.04 里运行出现这个问题怎么解决

### ISSUE THREAD

**Issue by ZhangQu** [shadowsocksr-backup/shadowsocksr#50]
输入 ： ssserver -p 443 -k password -m aes-256-cfb

输出：2019-04-26 20:46:19 INFO     loading libcrypto from libcrypto.so.1.0.0
2019-04-26 20:46:19 INFO     starting server at 0.0.0.0:443
Traceback (most recent call last):
  File "/usr/local/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.8.2', 'console_scripts', 'ssserver')()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/server.py", line 68, in main
    tcp_servers.append(tcprelay.TCPRelay(a_config, dns_resolver, False))
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/tcprelay.py", line 582, in __init__
    server_socket.bind(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied

**Comment by enjoy-binbin** [comment]
@ZhangQu sudo
