### ISSUE TITLE
centos7上启动报错，加密方式不支持chacha20-ietf

### ISSUE THREAD

**Issue by chaseSpace** [shadowsocksr-backup/shadowsocksr#67]
当config.json中method按以下方式配置时启动出错：
```
"method": "chacha20-ietf"
```
启动命令(py3.6也不行):
```
python shadowsocks/local.py -c config.json -d restart
```
exception：
```
Traceback (most recent call last):
  File "shadowsocks/local.py", line 81, in <module>
    main()
  File "shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/root/ssr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/root/ssr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/root/ssr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/root/ssr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/root/ssr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/root/ssr/shadowsocks/../shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/root/ssr/shadowsocks/../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
```
---
因为服务器那边我无法修改配置，所以只能适应那边，请问如何解决？是bug还是暂不支持这种加密方式？

**Comment by chaseSpace** [comment]
根据wiki解决了这个问题。
